codecov:
  notify:
    require_ci_to_pass: no

comment:
  layout: "header, diff, files"
  behavior: default
  require_changes: no
  branches:
    - main

coverage:
  precision: 2
  round: up
  range: "70...100"

parsers:
  gcov:
    branch_detection:
      conditional: yes
      loop: yes
      method: no
      macro: no

flags:
  unit-tests:
    paths:
      - tests/

