name: Python - py coverage test

on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - main
      - 'releases/*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v4
      with:
        ref: ${{ github.event.pull_request.head.sha }}
        fetch-depth: 0

    - name: Set up Python 3.11
      uses: actions/setup-python@v4
      with:
        python-version: "3.11"

    - name: Create coverage directory
      run: mkdir -p PYTHON/py/.qodana/code-coverage

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install coverage
      working-directory: PYTHON/py

    - name: Run tests with coverage
      run: |
        coverage run -m pytest -W ignore::DeprecationWarning
        coverage xml -o .qodana/code-coverage/coverage.xml
      working-directory: PYTHON/py

    - name: Archive coverage data
      uses: actions/upload-artifact@v4
      with:
        name: py-coverage-data
        path: PYTHON/py/.qodana/code-coverage

    - name: Qodana Scan
      uses: JetBrains/qodana-action@main
      env:
        QODANA_TOKEN: ${{ secrets.QODANA_TOKEN_845925216 }}
        QODANA_ENDPOINT: 'https://qodana.cloud'
      with:
        args: "-i,PYTHON/py,--linter,jetbrains/qodana-python:latest"
        pr-mode: false
