name: Qodana
on:
  workflow_dispatch:
  pull_request:
  push:
    branches: # Specify your branches here
      - main # The 'main' branch
      - 'releases/*' # The release branches

jobs:

  qodana:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
      checks: write
      actions: write
    steps:
      - name: Cleanup of Qodana caches
        run: |
          echo "Installing gh-actions-cache extension"
          gh extension install actions/gh-actions-cache || true
          echo "Listing all caches"
          gh cache list --repo ${{ github.repository }} --limit 1000 --json id,key > cache_list.json

          echo "Filtering caches matching 'qodana-*'"
          CACHE_IDS=$(jq -r '.[] | select(.key | startswith("qodana-")) | .id' cache_list.json)

          if [ -z "$CACHE_IDS" ]; then
            echo "No Qodana caches found to delete."
          else
            for CACHE_ID in $CACHE_IDS; do
              echo "Deleting cache with ID: $CACHE_ID"
              gh cache delete "$CACHE_ID" --repo ${{ github.repository }}
            done
            echo "Qodana caches deleted"
          fi
        env:
          GITHUB_TOKEN: ${{ secrets.ACTION_CLEAR_CACHES_TOKEN }}


      - uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.sha }}  # to check out the actual pull request commit, not the merge commit
          fetch-depth: 0  # a full history is required for pull request analysis

      - name: 'Qodana Scan'
        uses: JetBrains/qodana-action@v2024.2
        with:
          pr-mode: false
          args: --apply-fixes
          push-fixes: pull-request
        env:
          QODANA_TOKEN: ${{ secrets.QODANA_TOKEN_845925216 }}
          QODANA_ENDPOINT: 'https://qodana.cloud'
