name: Create Multi-Platform Release

on:
  push:
    tags:
      - 'v*'  # Activar el workflow solo en tags que comiencen con "v"

jobs:
  build-windows:
    runs-on: windows-latest
    steps:
    - name: Check out repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.12'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Build Windows executable with PyInstaller
      run: |
        pyinstaller run_game.spec

    - name: Upload Windows artifact
      uses: actions/upload-artifact@v3
      with:
        name: heroesvsmonsters-windows.exe
        path: dist\heroesvsmonsters.exe

  build-linux:
    runs-on: ubuntu-latest
    steps:
    - name: Check out repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.12'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Build Linux executable with PyInstaller
      run: |
        pyinstaller run_game.spec

    - name: Upload Linux artifact
      uses: actions/upload-artifact@v3
      with:
        name: heroesvsmonsters-linux
        path: dist/heroesvsmonsters

  build-macos:
    runs-on: macos-latest
    steps:
    - name: Check out repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.12'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Build macOS executable with PyInstaller
      run: |
        pyinstaller run_game.spec

    - name: Upload macOS artifact
      uses: actions/upload-artifact@v3
      with:
        name: heroesvsmonsters-macos
        path: dist/heroesvsmonsters

  release:
    needs: [build-windows, build-linux, build-macos]
    runs-on: ubuntu-latest
    steps:
    - name: Download Windows artifact
      uses: actions/download-artifact@v3
      with:
        name: heroesvsmonsters-windows.exe
        path: .

    - name: Download Linux artifact
      uses: actions/download-artifact@v3
      with:
        name: heroesvsmonsters-linux
        path: .

    - name: Download macOS artifact
      uses: actions/download-artifact@v3
      with:
        name: heroesvsmonsters-macos
        path: .

    - name: Install GitHub CLI
      run: |
        sudo apt update
        sudo apt install -y gh

    - name: Authenticate GitHub CLI
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        echo $GITHUB_TOKEN | gh auth login --with-token

    - name: Create GitHub Release with GitHub CLI
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        gh release create ${{ github.ref_name }} \
          ./heroesvsmonsters-windows.exe \
          ./heroesvsmonsters-linux \
          ./heroesvsmonsters-macos \
          --title "Release ${{ github.ref_name }}" \
          --notes "### Latest changes on this release:\n$(git log -n 10 --pretty=format:'- %s')"
